### ISSUE TITLE
link Fashion-MNIST readme to this notebook

### ISSUE THREAD

**Issue by hanxiao** [hwalsuklee/tensorflow-generative-model-collections#1]
Hi, I'm the author of Fashion-MNIST dataset. I found the GANs results on Fashion-MNIST is very interesting, especially how ACGAN and infoGAN failed on Fashion-MNIST. I already highlighted this notebook in Fashion-MNIST README.md. I hope it is ok for you. 🙇 

Here are the links: 
https://github.com/zalandoresearch/fashion-mnist#other-explorations-of-fashion-mnist
https://github.com/zalandoresearch/fashion-mnist/blob/master/README.zh-CN.md#生成对抗网络-gans

**Comment by hwalsuklee** [comment]
Sure!! I'm very glad to hear you mentioning on my repository.
