### ISSUE TITLE
where is the filter  'data' ?

### ISSUE THREAD

**Issue by LinBornRain** [hwalsuklee/tensorflow-generative-model-collections#15]
Hi @hwalsuklee !
It's a little bit odd that we can't find the filter 'data' ?
So we have to download mnist and fashion-mnist ?

**Comment by hwalsuklee** [comment]
Hi.

You are right.

You can download data from

mnist : http://yann.lecun.com/exdb/mnist/
fashion-mnist: https://github.com/zalandoresearch/fashion-mnist

Please notice that both mnist and fasion-mnist have files with the same name.
