### ISSUE TITLE
Bug in model constructors

### ISSUE THREAD

**Issue by goldsborough** [hwalsuklee/tensorflow-generative-model-collections#4]
You have this line in all the constructors:
```python
if dataset_name == 'mnist' or 'fashion-mnist':
```

It will always be `True`. You want `if dataset_name == 'mnist' or dataset_name == 'fashion-mnist'` or `if dataset_name in ['mnist', 'fashion-mnist']`.

**Comment by hwalsuklee** [comment]
Hi.
I just updated codes based on your comments.
Thanks for your contribution.
